cd c:\ARCHIVES
pkzip -r -p f:ARCHIVES
cd c:\BREAKOUT
pkzip -r -p f:BREAKOUT
cd c:\BRIEF   
pkzip -r -p f:BRIEF   
cd c:\BSHIP   
pkzip -r -p f:BSHIP   
cd c:\BU      
pkzip -r -p f:BU      
cd c:\CBREAK  
pkzip -r -p f:CBREAK  
cd c:\CCENT   
pkzip -r -p f:CCENT   
cd c:\CENT    
pkzip -r -p f:CENT    
cd c:\CFROG   
pkzip -r -p f:CFROG   
cd c:\COASTER 
pkzip -r -p f:COASTER 
cd c:\CSERVE  
pkzip -r -p f:CSERVE  
cd c:\DOS     
pkzip -r -p f:DOS     
cd c:\DP      
pkzip -r -p f:DP      
cd c:\EIGHT   
pkzip -r -p f:EIGHT   
cd c:\FROGGER 
pkzip -r -p f:FROGGER 
cd c:\GAMEBOY 
pkzip -r -p f:GAMEBOY 
cd c:\GBUTIL  
pkzip -r -p f:GBUTIL  
cd c:\GRAPHICS
pkzip -r -p f:GRAPHICS
cd c:\GWSDOS  
pkzip -r -p f:GWSDOS  
cd c:\INVESTOR
pkzip -r -p f:INVESTOR
cd c:\MAME    
pkzip -r -p f:MAME    
cd c:\MASM    
pkzip -r -p f:MASM    
cd c:\MISC    
pkzip -r -p f:MISC    
cd c:\NU      
pkzip -r -p f:NU      
cd c:\OLDWP   
pkzip -r -p f:OLDWP   
cd c:\QC2     
pkzip -r -p f:QC2     
cd c:\QUICKEN 
pkzip -r -p f:QUICKEN 
cd c:\TAX96   
pkzip -r -p f:TAX96   
cd c:\TAX97   
pkzip -r -p f:TAX97   
cd c:\TELIX   
pkzip -r -p f:TELIX   
cd c:\TEMP    
pkzip -r -p f:TEMP    
cd c:\UPLOAD  
pkzip -r -p f:UPLOAD  
cd c:\UTL     
pkzip -r -p f:UTL     
cd c:\WINFAX  
pkzip -r -p f:WINFAX  
cd c:\WINWORD 
pkzip -r -p f:WINWORD 
cd c:\WINWORD6
pkzip -r -p f:WINWORD6
